use_tls: false
host: localhost
port: 3000
repository_path: wikidata
repository_type: git
page_extension: .page
default_format: markdown
use_mathjax: true
feed_days: 14
use_cache: true
cache_dir: cache
front_page: Front Page
help_page: Help
max_upload_size: 1M
latex_engine: xelatex
